defmodule Fathom do
  @moduledoc """
  A program database for Elixir codebases.

  Fathom compiles a project under a compiler tracer and writes what the
  compiler resolved into SQLite: definitions, calls, module dependencies,
  behaviours, protocols, Ecto schemas, Phoenix routes, and the sites where
  dispatch is dynamic enough that the call graph stops being complete.

  Most use goes through the Mix tasks:

      mix fathom.install   # wire the database into AGENTS.md
      mix fathom.build     # compile under the tracer and write the database
      mix fathom.query     # run a read-only query

  This module is for reading the database from Elixir, which is mainly useful
  for building linters on top of it.

  ## Pieces

    * `Fathom.Tracer` — the compiler tracer, and what each event contributes
    * `Fathom.Dynamic` — finds dispatch the tracer structurally cannot see
    * `Fathom.Introspect` — post-compile reflection, including frameworks
    * `Fathom.Schema` — the database schema, and why it is shaped that way
    * `Fathom.Store` — the SQLite writer
    * `Fathom.Guide` — the agent-facing documentation generated by the installer
  """

  alias Exqlite.Sqlite3

  @default_path ".fathom/program.db"

  @doc "The conventional location of the database."
  def default_path, do: @default_path

  @doc """
  Runs a read-only query and returns `{:ok, columns, rows}`.

  The connection is opened read-only, so a statement that tries to write fails
  at SQLite rather than relying on anything here to inspect the SQL.

      iex> Fathom.query("SELECT mfa FROM functions WHERE name = ?", ["create_user"])

  """
  def query(sql, params \\ [], path \\ @default_path) do
    case Sqlite3.open(path, mode: :readonly) do
      {:ok, conn} ->
        try do
          with {:ok, stmt} <- Sqlite3.prepare(conn, sql),
               :ok <- Sqlite3.bind(stmt, params),
               {:ok, columns} <- Sqlite3.columns(conn, stmt),
               {:ok, rows} <- Sqlite3.fetch_all(conn, stmt) do
            Sqlite3.release(conn, stmt)
            {:ok, columns, rows}
          end
        after
          Sqlite3.close(conn)
        end

      {:error, reason} ->
        {:error, reason}
    end
  end

  @doc """
  Runs a query and returns its rows as maps keyed by column name.

  Raises if the query fails.
  """
  def query!(sql, params \\ [], path \\ @default_path) do
    case query(sql, params, path) do
      {:ok, columns, rows} ->
        Enum.map(rows, fn row -> columns |> Enum.zip(row) |> Map.new() end)

      {:error, reason} ->
        raise "fathom query failed: #{inspect(reason)}"
    end
  end

  @doc """
  Asserts that a query returns no rows, which is how architecture rules are
  written.

  Returns `:ok`, or `{:error, rows}` with the violations.

      Fathom.forbid(\"\"\"
      SELECT caller, file, line FROM calls
      WHERE caller_module LIKE 'MyAppWeb.%' AND callee_module LIKE '%.Repo'
      \"\"\")

  """
  def forbid(sql, params \\ [], path \\ @default_path) do
    case query!(sql, params, path) do
      [] -> :ok
      rows -> {:error, rows}
    end
  end
end
