defmodule Fathom.Guide do
  @moduledoc """
  The agent-facing documentation for a project's program database.

  `mix fathom.install` writes this into the project's `AGENTS.md`. It is the
  part that decides whether the database gets used: an agent that cannot see
  the schema will fall back to grep, and an agent given the schema with no
  worked examples will write queries that return nothing and then fall back to
  grep anyway.
  """

  alias Fathom.Schema

  @begin "<!-- fathom:begin -->"
  @end_marker "<!-- fathom:end -->"

  @doc "Markers delimiting the generated section, so it can be regenerated in place."
  def markers, do: {@begin, @end_marker}

  @doc "The full generated section, including its markers."
  def section(db_path) do
    """
    #{@begin}
    ## Querying this codebase

    This project has a program database at `#{db_path}`: a SQLite file built by
    compiling the project under a tracer, holding its symbols, call graph,
    module dependencies and framework facts.

    Prefer it over grep for any structural question — where something is
    defined, what calls what, what depends on what. Grep matches text, and in
    Elixir a great deal of what runs is generated by macros and never appears
    as text anywhere. The database records what the compiler resolved after
    macro expansion, so a `use Phoenix.LiveView` that generates a dozen
    callbacks shows up as a dozen definitions.

    Query it with either:

    ```
    sqlite3 #{db_path} "SELECT ..."
    mix fathom.query "SELECT ..."
    ```

    Rebuild it with `mix fathom.build` after changing code. It is a derived
    artefact and is not committed.

    ### Schema

    `mfa` columns are strings like `"MyApp.Accounts.create_user/2"` and are the
    join key between tables. Every row that refers to a function also carries
    its module, so most questions need no join at all.

    ```sql
    #{Schema.to_ddl()}
    ```

    ### Worked queries

    **Where is something defined?**

    ```sql
    SELECT mfa, kind, file, line FROM functions WHERE name = 'create_user';
    ```

    **What is its documentation and spec?**

    ```sql
    SELECT signature, spec, doc FROM functions WHERE mfa = 'MyApp.Accounts.create_user/2';
    ```

    **Who calls it directly?**

    ```sql
    SELECT caller, file, line FROM calls WHERE callee = 'MyApp.Accounts.create_user/2';
    ```

    **Which public functions reach it, however indirectly?**

    This is the question grep cannot answer, because the path runs through
    private functions that share no name with the target.

    ```sql
    WITH RECURSIVE up(mfa) AS (
      SELECT caller FROM calls WHERE callee = 'MyApp.Repo.delete_all/1'
      UNION
      SELECT c.caller FROM calls c JOIN up ON c.callee = up.mfa
    )
    SELECT f.mfa, f.file, f.line
    FROM functions f JOIN up USING (mfa)
    WHERE f.kind = 'def';
    ```

    **What does this function reach?** Swap the direction:

    ```sql
    WITH RECURSIVE down(mfa) AS (
      SELECT callee FROM calls WHERE caller = 'MyAppWeb.UserController.delete/2'
      UNION
      SELECT c.callee FROM calls c JOIN down ON c.caller = down.mfa
    )
    SELECT DISTINCT mfa FROM down ORDER BY mfa;
    ```

    **Which HTTP endpoints eventually touch a given table?**

    This joins three things no single tool has together: the router's routes,
    the call graph, and what Ecto knows about which schema backs which table.

    ```sql
    WITH RECURSIVE reach(verb, path, mfa) AS (
      SELECT r.verb, r.path, r.plug || '.' || r.action || '/2' FROM routes r
      UNION
      SELECT re.verb, re.path, c.callee
      FROM calls c JOIN reach re ON c.caller = re.mfa
    )
    SELECT DISTINCT re.verb, re.path
    FROM reach re
    JOIN struct_uses su ON su.caller = re.mfa
    JOIN schemas s ON s.module = su.struct_module
    WHERE s.source = 'applications';
    ```

    Two caveats. Carrying the route through the recursion makes this the most
    expensive query here, since the working set is one row per route per
    reachable function. And the `'/2'` assumes a controller action; LiveView
    routes all share `Phoenix.LiveView.Plug` as their `plug`, so start those
    from the module in `routes.action` instead.

    **How complete is the call graph here?**

    Elixir can dispatch in ways no static graph can follow: `apply/3`, a module
    held in a variable or read from config, a protocol. Those sites are
    recorded rather than hidden, so you can tell when an answer is partial.

    ```sql
    SELECT caller, kind, file, line FROM dynamic_sites
    WHERE caller_module LIKE 'MyApp.Accounts%';
    ```

    **What does this module depend on, and when?**

    ```sql
    SELECT to_module, type FROM module_deps WHERE from_module = 'MyApp.Accounts';
    ```

    `compile` dependencies are the expensive ones: changing the target forces a
    recompile of the source.

    **Who implements a behaviour, or a protocol?**

    ```sql
    SELECT module FROM behaviours WHERE behaviour = 'GenServer';
    SELECT module, for_type FROM impls WHERE protocol = 'Jason.Encoder';
    ```

    **What does this Ecto schema look like?**

    ```sql
    SELECT s.source, f.field, f.type FROM schemas s
    JOIN schema_fields f USING (module)
    WHERE s.module = 'MyApp.Accounts.User';

    SELECT name, cardinality, related FROM schema_assocs
    WHERE module = 'MyApp.Accounts.User';
    ```

    **Which public functions are never called?** Dead code, or a public API.

    ```sql
    SELECT f.mfa, f.file, f.line FROM functions f
    LEFT JOIN calls c ON c.callee = f.mfa
    WHERE f.kind = 'def' AND c.callee IS NULL AND f.generated = 0
      AND NOT EXISTS (
        SELECT 1 FROM routes r WHERE r.plug = f.module AND r.action = f.name
      )
      AND NOT EXISTS (
        SELECT 1 FROM callbacks cb JOIN behaviours b ON b.behaviour = cb.module
        WHERE b.module = f.module AND cb.name = f.name AND cb.arity = f.arity
      )
    ORDER BY f.module;
    ```

    The three exclusions all matter. `generated = 0` drops functions a macro
    produced rather than someone writing them: `use Ecto.Repo` alone defines
    around seventy public functions, most of which any given application never
    calls. The other two drop functions that are called, just not by anything
    the call graph can see — a controller action is invoked by the router, and
    a behaviour callback by the library that defined it.

    Even then, treat the result as a list of candidates. Anything reached only
    from tests looks dead here, because the database is built from a `dev`
    compile which does not include them.

    ### Architecture rules

    A rule is a query that should return no rows. These work as linters in CI,
    and you can propose new ones the same way.

    ```sql
    -- The web layer must go through a context, never straight to the repo.
    SELECT caller, file, line FROM calls
    WHERE caller_module LIKE 'MyAppWeb.%' AND callee_module LIKE '%.Repo';

    -- Contexts must not reach into each other's internals.
    SELECT from_module, to_module FROM module_deps
    WHERE from_module LIKE 'MyApp.Accounts.%' AND to_module LIKE 'MyApp.Billing.%';
    ```

    ### What the database does not know

    It is built from one compilation, so it covers this project's own code and
    not its dependencies. It records calls the compiler resolved; runtime wiring
    such as telemetry handlers, Oban workers invoked by the library, or a process
    looked up by registered name leave no edge. Check `dynamic_sites` before
    concluding that nothing calls something.
    #{@end_marker}
    """
  end
end
